resolver: lts-10.3
packages:
- '.'
- '../../libs/bilge'
- '../../libs/brig-types'
- '../../libs/cassandra-util'
- '../../libs/galley-types'
- '../../libs/gundeck-types'
- '../../libs/http-client-openssl-ext'
- '../../libs/metrics-core'
- '../../libs/metrics-wai'
- '../../libs/tasty-cannon'
- '../../libs/types-common'
- '../../libs/types-common-journal'
- '../../libs/wai-utilities'

flags:
  types-common:
    cql: True
    protobuf: True
    arbitrary: True

extra-deps:
- currency-codes-2.0.0.0
- data-timeout-0.3
- wai-middleware-gunzip-0.0.2
- HsOpenSSL-0.11.4.12
